/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import QImg8Image from 'src/assets/images/BirthdayPt2_Q_img8.png';
import QImg7Image from 'src/assets/images/BirthdayPt2_Q_img7.png';
import QImg6Image from 'src/assets/images/BirthdayPt2_Q_img6.png';
import QImg5Image from 'src/assets/images/BirthdayPt2_Q_img5.png';
import QImg3Image from 'src/assets/images/BirthdayPt2_Q_img3.png';
import QImg4Image from 'src/assets/images/BirthdayPt2_Q_img4.png';
import QImg2Image from 'src/assets/images/BirthdayPt2_Q_img2.png';
import QImg1Image from 'src/assets/images/BirthdayPt2_Q_img1.png';
import { styled } from '@mui/material/styles';
import QuizButtonsM from 'src/components/QuizButtonsM/QuizButtonsM';
import QuizButtonsD from 'src/components/QuizButtonsD/QuizButtonsD';
import { animated, useSpring, easings } from 'react-spring';

 
const Property1BrithdayPt2 = animated(styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  height: `770px`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
}));
  
const Qs = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  zIndex: `1`,  
  margin: `0px`,  
});
  
const Q3Start = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Q3Up4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const Q3Up3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q3Up2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q3Up1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const QuestionAndButtons34 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `211px`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons33 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons32 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `49px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const Q3SlideOut4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q3SlideOut3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q3SlideOut2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q3SlideOut = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const WhatCognacStyleAreYo = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Hennessy Sans`,  
  fontWeight: `400`,  
  fontSize: `42px`,  
  letterSpacing: `1.68px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const Q3BtnsM = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `34px 0px 0px 0px`,  
});
  
const QuizButtonsM5 = styled(QuizButtonsM)(({ theme }) =>({  
  height: `47.9px`,  
  margin: `0px`,  
}));
  
const QuizButtonsM6 = styled(QuizButtonsM)(({ theme }) =>({  
  height: `47.9px`,  
  margin: `19px 0px 0px 0px`,  
}));
  
const Q3BtnsD = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `34px 0px 0px 0px`,  
});
  
const QuizButtonsD5 = styled(QuizButtonsD)(({ theme }) =>({  
  height: `78.01px`,  
  margin: `0px`,  
}));
  
const QuizButtonsD6 = styled(QuizButtonsD)(({ theme }) =>({  
  height: `78.01px`,  
  margin: `0px 0px 0px 50px`,  
}));
  
const Q2Start = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `-211px 0px 0px 0px`,  
});
  
const Q2Up4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const Q2Up3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q2Up2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q2Up1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const QuestionAndButtons24 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `211px`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons23 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons22 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `49px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const Q2SlideOut4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `162.01px`,  
  margin: `0px`,  
});
  
const Q2SlideOut3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `162.01px`,  
  margin: `0px`,  
});
  
const Q2SlideOut2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `162.01px`,  
  margin: `0px`,  
});
  
const Q2SlideOut = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `162.01px`,  
  margin: `0px`,  
});
  
const WhatFlavorsDoYouPref = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Hennessy Sans`,  
  fontWeight: `400`,  
  fontSize: `42px`,  
  letterSpacing: `1.68px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const Q2BtnsM = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `34px 0px 0px 0px`,  
});
  
const QuizButtonsM3 = styled(QuizButtonsM)(({ theme }) =>({  
  height: `47.9px`,  
  margin: `0px`,  
}));
  
const QuizButtonsM4 = styled(QuizButtonsM)(({ theme }) =>({  
  height: `47.9px`,  
  margin: `19px 0px 0px 0px`,  
}));
  
const Q2BtnsD = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `34px 0px 0px 0px`,  
});
  
const QuizButtonsD3 = styled(QuizButtonsD)(({ theme }) =>({  
  height: `78.01px`,  
  margin: `0px`,  
}));
  
const QuizButtonsD4 = styled(QuizButtonsD)(({ theme }) =>({  
  height: `78.01px`,  
  margin: `0px 0px 0px 50px`,  
}));
  
const QuestionAndButtons14 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `211px`,  
  width: `1440px`,  
  margin: `-211px 0px 0px 0px`,  
});
  
const QuestionAndButtons13 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons12 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const QuestionAndButtons1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `49px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `211px`,  
  margin: `0px`,  
});
  
const Q1SlideOut4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q1SlideOut3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q1SlideOut2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Q1SlideOut = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const WhichOfTheseBestDesc = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Hennessy Sans`,  
  fontWeight: `400`,  
  fontSize: `42px`,  
  letterSpacing: `1.68px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  width: `1440px`,  
  margin: `0px`,  
});
  
const Q1BtnsM = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `34px 0px 0px 0px`,  
});
  
const QuizButtonsM1 = styled(QuizButtonsM)(({ theme }) =>({  
  height: `47.9px`,  
  margin: `0px`,  
}));
  
const QuizButtonsM2 = styled(QuizButtonsM)(({ theme }) =>({  
  height: `47.9px`,  
  margin: `19px 0px 0px 0px`,  
}));
  
const Q1BtnsD = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `34px 0px 0px 0px`,  
});
  
const QuizButtonsD1 = styled(QuizButtonsD)(({ theme }) =>({  
  height: `78.01px`,  
  margin: `0px`,  
}));
  
const QuizButtonsD2 = styled(QuizButtonsD)(({ theme }) =>({  
  height: `78.01px`,  
  margin: `0px 0px 0px 50px`,  
}));
  
const QuestionShapes = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `650.5px`,  
  width: `2596.5px`,  
  zIndex: `0`,  
  left: `0px`,  
  top: `133px`,  
});
  
const SlideBottles6B = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles6A = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles5B = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles5A = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles4B = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles4A = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles3B = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles3A = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles2B = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles2A = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles1B = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SlideBottles1A = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `2596.5px`,  
  height: `650.5px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const QImg8 = styled("img")({  
  height: `649px`,  
  width: `324.5px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `2272px`,  
  top: `0px`,  
});
  
const QImg7 = styled("img")({  
  height: `324.5px`,  
  width: `324.5px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `1947px`,  
  top: `1px`,  
});
  
const QImg6 = styled("img")({  
  height: `324.5px`,  
  width: `324.5px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `1947px`,  
  top: `326px`,  
});
  
const QImg5 = styled("img")({  
  height: `649px`,  
  width: `649px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `1298px`,  
  top: `1px`,  
});
  
const QImg3 = styled("img")({  
  height: `649px`,  
  width: `649px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `649px`,  
  top: `1px`,  
});
  
const QImg4 = styled("img")({  
  height: `324.5px`,  
  width: `324.5px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `973px`,  
  top: `325px`,  
});
  
const QImg2 = styled("img")({  
  height: `649px`,  
  width: `649px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const QImg1 = styled("img")({  
  height: `324.5px`,  
  width: `324.5px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `0px`,  
  top: `325px`,  
});
 
function BirthdayPt2(props) {
  
  
  const [Property1BrithdayPt2Spring, Property1BrithdayPt2Api] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeInOutExpo']
    },
    delay: 0,
    from: { opacity: 1  },
  }));
  return (
    <Property1BrithdayPt2  className={props.className}    style={{ ...Property1BrithdayPt2Spring }}>
      <Qs >
        {(props.step === 3) &&
          <Q3Start >
            <Q3Up4 >
              <Q3Up3 >
                <Q3Up2 >
                  <Q3Up1 >
                    <QuestionAndButtons34 >
                      <QuestionAndButtons33 >
                        <QuestionAndButtons32 >
                          <QuestionAndButtons3 >
                            <Q3SlideOut4 >
                              <Q3SlideOut3 >
                                <Q3SlideOut2 >
                                  <Q3SlideOut >
                                    <WhatCognacStyleAreYo >
                                      {`What cognac style are you?`}
                                        </WhatCognacStyleAreYo>
                                    {false &&
                                      <Q3BtnsM >
                                        <QuizButtonsM5   />
                                        <QuizButtonsM6   />
                                      </Q3BtnsM>
                                    }
                                    <Q3BtnsD >
                                      <QuizButtonsD5   />
                                      <QuizButtonsD6   />
                                    </Q3BtnsD>
                                  </Q3SlideOut>
                                </Q3SlideOut2>
                              </Q3SlideOut3>
                            </Q3SlideOut4>
                          </QuestionAndButtons3>
                        </QuestionAndButtons32>
                      </QuestionAndButtons33>
                    </QuestionAndButtons34>
                  </Q3Up1>
                </Q3Up2>
              </Q3Up3>
            </Q3Up4>
          </Q3Start>
        }
        {(props.step === 2) &&
          <Q2Start >
            <Q2Up4 >
              <Q2Up3 >
                <Q2Up2 >
                  <Q2Up1 >
                    <QuestionAndButtons24 >
                      <QuestionAndButtons23 >
                        <QuestionAndButtons22 >
                          <QuestionAndButtons2 >
                            <Q2SlideOut4 >
                              <Q2SlideOut3 >
                                <Q2SlideOut2 >
                                  <Q2SlideOut >
                                    <WhatFlavorsDoYouPref >
                                      {`What flavors do you prefer?`}
                                        </WhatFlavorsDoYouPref>
                                    {false &&
                                      <Q2BtnsM >
                                        <QuizButtonsM3   />
                                        <QuizButtonsM4   />
                                      </Q2BtnsM>
                                    }
                                    <Q2BtnsD >
                                      <QuizButtonsD3   />
                                      <QuizButtonsD4   />
                                    </Q2BtnsD>
                                  </Q2SlideOut>
                                </Q2SlideOut2>
                              </Q2SlideOut3>
                            </Q2SlideOut4>
                          </QuestionAndButtons2>
                        </QuestionAndButtons22>
                      </QuestionAndButtons23>
                    </QuestionAndButtons24>
                  </Q2Up1>
                </Q2Up2>
              </Q2Up3>
            </Q2Up4>
          </Q2Start>
        }
        {(props.step === 1) &&
          <QuestionAndButtons14 >
            <QuestionAndButtons13 >
              <QuestionAndButtons12 >
                <QuestionAndButtons1 >
                  <Q1SlideOut4 >
                    <Q1SlideOut3 >
                      <Q1SlideOut2 >
                        <Q1SlideOut >
                          <WhichOfTheseBestDesc >
                            {`Which of these best describe you?`}
                              </WhichOfTheseBestDesc>
                          {false &&
                            <Q1BtnsM >
                              <QuizButtonsM1   />
                              <QuizButtonsM2   />
                            </Q1BtnsM>
                          }
                          <Q1BtnsD >
                            <QuizButtonsD1   />
                            <QuizButtonsD2   onMouseOver={() => {  Property1BrithdayPt2Api.start({ ...{ opacity: 0  }, delay: 0 }); }} onMouseOut={() => {  Property1BrithdayPt2Api.start({ opacity: 1  }); }} />
                          </Q1BtnsD>
                        </Q1SlideOut>
                      </Q1SlideOut2>
                    </Q1SlideOut3>
                  </Q1SlideOut4>
                </QuestionAndButtons1>
              </QuestionAndButtons12>
            </QuestionAndButtons13>
          </QuestionAndButtons14>
        }
      </Qs>
      <QuestionShapes >
        <SlideBottles6B >
          <SlideBottles6A >
            <SlideBottles5B >
              <SlideBottles5A >
                <SlideBottles4B >
                  <SlideBottles4A >
                    <SlideBottles3B >
                      <SlideBottles3A >
                        <SlideBottles2B >
                          <SlideBottles2A >
                            <SlideBottles1B >
                              <SlideBottles1A >
                                <QImg8  src={QImg8Image} alt={"Q_img8"}/>
                                <QImg7  src={QImg7Image} alt={"Q_img7"}/>
                                <QImg6  src={QImg6Image} alt={"Q_img6"}/>
                                <QImg5  src={QImg5Image} alt={"Q_img5"}/>
                                <QImg3  src={QImg3Image} alt={"Q_img3"}/>
                                <QImg4  src={QImg4Image} alt={"Q_img4"}/>
                                <QImg2  src={QImg2Image} alt={"Q_img2"}/>
                                <QImg1  src={QImg1Image} alt={"Q_img1"}/>
                              </SlideBottles1A>
                            </SlideBottles1B>
                          </SlideBottles2A>
                        </SlideBottles2B>
                      </SlideBottles3A>
                    </SlideBottles3B>
                  </SlideBottles4A>
                </SlideBottles4B>
              </SlideBottles5A>
            </SlideBottles5B>
          </SlideBottles6A>
        </SlideBottles6B>
      </QuestionShapes>
    </Property1BrithdayPt2>
  );
}

export default BirthdayPt2;
