/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Shape3 from 'components/Shape3/Shape3';
import ImageTest from 'components/ImageTest/ImageTest';
import { Frame23Props } from 'types';

 
const Frame231: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `5px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `60px 10px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const Shape31: any = styled(Shape3)(({ theme }: any) =>({  
  width: `153px`,  
  height: `157px`,  
  margin: `0px`,  
}));
  
const Shape4Rotated: any = styled("img")({  
  height: `157px`,  
  width: `153px`,  
  margin: `0px 0px 0px 34px`,  
});
  
const Gettyimages125755349: any = styled("img")({  
  height: `237px`,  
  width: `218px`,  
  objectFit: `cover`,  
  margin: `0px 0px 0px 34px`,  
});
  
const Frame24: any = styled("div")({  
  backgroundColor: `rgba(188, 44, 53, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `244px`,  
  height: `225px`,  
  margin: `0px 0px 0px 34px`,  
  overflow: `hidden`,  
});
  
const ImageTest1: any = styled(ImageTest)(({ theme }: any) =>({  
  width: `153px`,  
  height: `157px`,  
  margin: `0px 0px 0px 34px`,  
}));
 
function Frame23(props: Frame23Props): JSX.Element {
  return (
    <Frame231  className={props.className}   >
      <Shape31   />
      <Shape4Rotated  src={`assets/images/Frame23_Shape4___rotated.png`} alt={"Shape4 - rotated"}/>
      <Gettyimages125755349  src={`assets/images/Frame23_gettyimages_1257553494_1.png`} alt={"gettyimages-1257553494 1"}/>
      <Frame24 >
      </Frame24>
      <ImageTest1   />
    </Frame231>
  );
}

export default Frame23;
