/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Frame14 from 'src/components/Frame14/Frame14';
import { Frame20Props } from 'src/types';

 
const Frame201: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `24px 33px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const Frame141: any = styled(Frame14)(({ theme }: any) =>({  
  margin: `0px`,  
}));
 
function Frame20(props: Frame20Props): JSX.Element {
  return (
    <Frame201  className={props.className}   >
      {undefined && undefined.map((undefined: any, index: number) => {
        return (
          <Frame141  key={index}  />
        )
      })}
    </Frame201>
  );
}

export default Frame20;
