/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import { styled } from '@mui/material/styles';
import { animated, useSpring, easings } from 'react-spring';

 
const Property1Default = animated(styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `371px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
}));
  
const Frame26 = animated(styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `231px`,  
  height: `217px`,  
  left: `87px`,  
  top: `89px`,  
  overflow: `hidden`,  
}));
  
const Hello = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `900`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `33px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `74px`,  
  top: `92px`,  
});
 
function Frame25(props) {
  
  
  const [Property1DefaultSpring, Property1DefaultApi] = useSpring(() => ({
    config: {
      duration: 1000,
      easing: easings['easeInOutQuint']
    },
    delay: 0,
    from: { transform: "translateY(0px) scale(-0.25)" , opacity: 1  },
  }));

  const [Frame26Spring, Frame26Api] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeOutExpo']
    },
    delay: 0,
    from: { opacity: 0  },
  }));

  React.useEffect(() => {
    Frame26Api.start({ ...{ opacity: 1  }, delay: 0, config: { duration: 250 } });
    }, []);       
 
  return (
    <Property1Default onClick={() => {  Property1DefaultApi.start({ ...{ transform: "translateY(100px) scale(1.4)" , opacity: 0  }, delay: 0 });  }}  className={props.className}    style={{ ...Property1DefaultSpring }}>
      <Helmet>
        <title>Frame 25</title>
      </Helmet>
      <Frame26  style={{ ...Frame26Spring }}>
        <Hello >
          {`Hello`}
            </Hello>
      </Frame26>
    </Property1Default>
  );
}

export default Frame25;
