/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

 
const StateDefault = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  height: `44px`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 10px 0px 0px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const Rectangle1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  width: `6px`,  
  height: `44px`,  
  margin: `0px`,  
});
  
const About = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: theme.typography["Typography"]["Body 1"].fontStyle,  
  fontFamily: theme.typography["Typography"]["Body 1"].fontFamily,  
  fontWeight: theme.typography["Typography"]["Body 1"].fontWeight,  
  fontSize: theme.typography["Typography"]["Body 1"].fontSize,  
  letterSpacing: theme.typography["Typography"]["Body 1"].letterSpacing,  
  textDecoration: theme.typography["Typography"]["Body 1"].textDecoration,  
  lineHeight: theme.typography["Typography"]["Body 1"].lineHeight,  
  textTransform: theme.typography["Typography"]["Body 1"].textTransform,  
  margin: `0px 0px 0px 10px`,  
}));
 
function Link1(props) {
  
    return (
    <StateDefault  className={props.className}   >
      <Rectangle1 >
      </Rectangle1>
      <About >
        {`About`}
          </About>
    </StateDefault>
  );
}

export default Link1;
