/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

 
const Property1Default = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  border: `1px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `45px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "auto",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  overflow: `hidden`,  
});
  
const Rectangle1 = styled("div")({  
  backgroundColor: `rgba(217, 217, 217, 1)`,  
  width: `46px`,  
  height: `46px`,  
  position: `absolute`,  
  left: `53px`,  
  top: `25px`,  
});
 
function Frame7(props) {
  
    return (
    <Property1Default  className={props.className}   >
      <Rectangle1 >
      </Rectangle1>
    </Property1Default>
  );
}

export default Frame7;
