/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

 
const Frame291 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Rectangle3 = styled("div")({  
  backgroundColor: `rgba(254, 31, 31, 1)`,  
  width: `928px`,  
  height: `212px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
 
function Frame29(props) {
  
    return (
    <Frame291  className={props.className}   >
      <Rectangle3 >
      </Rectangle3>
    </Frame291>
  );
}

export default Frame29;
