/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame7 from 'src/components/Frame7/Frame7';
import useFrame6Frame3 from 'src/components/Frame6Frame3/useFrame6Frame3';
 
const Frame6Frame31 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `14px 27px`,  
  boxSizing: `border-box`,  
  height: "auto",  
  width: "100vh",  
});
  
const Frame71 = styled(Frame7)(({ theme }) =>({  
  height: `97px`,  
  width: `153px`,  
  margin: `0px`,  
}));
 
function Frame6Frame3(props) {
  const {data} = useFrame6Frame3();
  
    return (
    <Frame6Frame31  className={props.className}   >
      {(data.eee) &&
        <Frame71   />
      }
    </Frame6Frame31>
  );
}

export default Frame6Frame3;
