/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import MovieImageImage from 'src/assets/images/MovieHomePage_movie_image.png';
import PromoImgCroppedImage from 'src/assets/images/MovieHomePage_promo_img_cropped.png';
import CardImageCroppedImage from 'src/assets/images/MovieHomePage_card_image_cropped.png';
import MovieNavbar from 'src/components/MovieNavbar/MovieNavbar';
import BuyTicketBtn from 'src/components/BuyTicketBtn/BuyTicketBtn';
import SlideshowProgress from 'src/components/SlideshowProgress/SlideshowProgress';
import HpMovieThumbnail from 'src/components/HpMovieThumbnail/HpMovieThumbnail';
import SecondaryBtn from 'src/components/SecondaryBtn/SecondaryBtn';
import MovieFooter from 'src/components/MovieFooter/MovieFooter';

 
const ScreenMobile = styled("div")(({ theme }) =>({  
  backgroundColor: theme.palette["Background"]["Default"],  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: `375px`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
  height: `4935.57px`,  
}));
  
const MovieNavbar1 = styled(MovieNavbar)(({ theme }) =>({  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const TopAndMask = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Top = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const MovieImage = styled("div")({  
  backgroundImage: `url(${MovieImageImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `10px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  height: `456px`,  
  margin: `0px`,  
});
  
const TitleDarkened = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `375px`,  
  height: `456px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const TitleMask = styled("div")({  
  background: `linear-gradient(39.69deg, rgba(0, 0, 0, 1) 1.244188344165035%, rgba(0, 0, 0, 0) 47.14643601850167%)`,  
  height: `402px`,  
  width: `638px`,  
  margin: `0px`,  
});
  
const TitleAndBuy = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-end`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `254px`,  
  left: `27px`,  
  top: `98px`,  
});
  
const MovieTitle = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Description = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const BuyTicketBtn1 = styled(BuyTicketBtn)(({ theme }) =>({  
  margin: `24px 0px 0px 0px`,  
}));
  
const SlideshowProgress1 = styled(SlideshowProgress)(({ theme }) =>({  
  margin: `0px`,  
}));
  
const ContentAndMask = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-end`,  
  alignItems: `center`,  
  padding: `40px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const SecNowPlaying = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 24px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const CardInfo = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Movies = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const NowPlaying = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Thumbnails = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `14px 0px 0px 0px`,  
});
  
const HpMovieThumbnail1 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail2 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail3 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail4 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail5 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail6 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail7 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `14px 0px 0px 0px`,  
});
  
const HpMovieThumbnail8 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail9 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `14px 0px 0px 0px`,  
});
  
const HpMovieThumbnail10 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail11 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const SecPromos = styled("div")({  
  backgroundColor: `rgba(23, 23, 23, 1)`,  
  borderRadius: `16px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 24px 60px 24px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
  overflow: `hidden`,  
});
  
const Promo1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const PromoImgCropped = styled("div")({  
  backgroundImage: `url(${PromoImgCroppedImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  borderRadius: `10px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `300px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const PromoInfo = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
});
  
const Txt = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const GetItPoppinAtHomeOrO = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Description1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0.8)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const SecondaryBtn1 = styled(SecondaryBtn)(({ theme }) =>({  
  margin: `18px 0px 0px 0px`,  
}));
  
const Promo2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 10px 30px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `20px 0px 0px 0px`,  
});
  
const CardImageCropped = styled("div")({  
  backgroundImage: `url(${CardImageCroppedImage})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  borderRadius: `10px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `300px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const CardInfo1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
});
  
const Txt1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const ApplyForAPrePaidCard = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `600`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Description2 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0.8)`,  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `400`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const BuyTicketBtn2 = styled(BuyTicketBtn)(({ theme }) =>({  
  margin: `18px 0px 0px 0px`,  
}));
  
const SecComingSoon = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `30px 24px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
});
  
const CardInfo2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Movies1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const ComingSoon = styled("div")(({ theme }) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: theme.palette["Text"]["Primary"],  
  fontStyle: `normal`,  
  fontFamily: `Roboto`,  
  fontWeight: `900`,  
  fontSize: `22px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
  
const Thumbnails3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `10px 0px 0px 0px`,  
});
  
const HpMovieThumbnail12 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail13 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail14 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail15 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail16 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail17 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const HpMovieThumbnail18 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `10px 0px 0px 0px`,  
});
  
const HpMovieThumbnail19 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail20 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const Thumbnails5 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `10px 0px 0px 0px`,  
});
  
const HpMovieThumbnail21 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px`,  
}));
  
const HpMovieThumbnail22 = styled(HpMovieThumbnail)(({ theme }) =>({  
  width: `150px`,  
  height: `261px`,  
  margin: `0px 0px 0px 18px`,  
}));
  
const MovieFooter1 = styled(MovieFooter)(({ theme }) =>({  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
 
function MovieHomePage(props) {
  
    return (
    <ScreenMobile  className={props.className}   >
      <MovieNavbar1   />
      <TopAndMask >
        <Top >
          <MovieImage >
            <TitleDarkened >
              <TitleMask >
              </TitleMask>
            </TitleDarkened>
            <TitleAndBuy >
              <MovieTitle >
                {`Hero Movie catchy description to drive CTA button`}
                  </MovieTitle>
              <Description >
                {`Catchy description to drive CTA button lorem ipsum not to be read but just to fill space and exists as a placeholder to get a feel for content.`}
                  </Description>
              <BuyTicketBtn1   />
            </TitleAndBuy>
            <SlideshowProgress1   />
          </MovieImage>
        </Top>
        <ContentAndMask >
          <SecNowPlaying >
            <CardInfo >
              <Movies >
                <NowPlaying >
                  {`Now Playing`}
                    </NowPlaying>
                <Thumbnails >
                  <HpMovieThumbnail1   />
                  <HpMovieThumbnail2   />
                  {false &&
                    <HpMovieThumbnail3   />
                  }
                  {false &&
                    <HpMovieThumbnail4   />
                  }
                  {false &&
                    <HpMovieThumbnail5   />
                  }
                  {false &&
                    <HpMovieThumbnail6   />
                  }
                  {false &&
                    <HpMovieThumbnail7   />
                  }
                </Thumbnails>
                <Thumbnails1 >
                  <HpMovieThumbnail8   />
                  <HpMovieThumbnail9   />
                </Thumbnails1>
                <Thumbnails2 >
                  <HpMovieThumbnail10   />
                  <HpMovieThumbnail11   />
                </Thumbnails2>
              </Movies>
            </CardInfo>
          </SecNowPlaying>
          <SecPromos >
            <Promo1 >
              <PromoImgCropped >
              </PromoImgCropped>
              <PromoInfo >
                <Txt >
                  <GetItPoppinAtHomeOrO >
                    {`Get It Poppin’ at Home or on the Go`}
                      </GetItPoppinAtHomeOrO>
                  <Description1 >
                    {`Get that classic Nuvu theater popcorn taste at home. Packaged for carryout, so you can enjoy at game nights, parties, relaxing on the couch, and more.`}
                      </Description1>
                </Txt>
                <SecondaryBtn1   />
              </PromoInfo>
            </Promo1>
            <Promo2 >
              <CardImageCropped >
              </CardImageCropped>
              <CardInfo1 >
                <Txt1 >
                  <ApplyForAPrePaidCard >
                    {`Apply for a pre-paid card and get discounts and benefits`}
                      </ApplyForAPrePaidCard>
                  <Description2 >
                    {`Catchy description to drive CTA button lorem ipsum not to be read but just to fill space and exists as a placeholder to get a feel for content.`}
                      </Description2>
                </Txt1>
                <BuyTicketBtn2   />
              </CardInfo1>
            </Promo2>
          </SecPromos>
          <SecComingSoon >
            <CardInfo2 >
              <Movies1 >
                <ComingSoon >
                  {`Coming Soon`}
                    </ComingSoon>
                <Thumbnails3 >
                  <HpMovieThumbnail12   />
                  <HpMovieThumbnail13   />
                  {false &&
                    <HpMovieThumbnail14   />
                  }
                  {false &&
                    <HpMovieThumbnail15   />
                  }
                  {false &&
                    <HpMovieThumbnail16   />
                  }
                  {false &&
                    <HpMovieThumbnail17   />
                  }
                  {false &&
                    <HpMovieThumbnail18   />
                  }
                </Thumbnails3>
                <Thumbnails4 >
                  <HpMovieThumbnail19   />
                  <HpMovieThumbnail20   />
                </Thumbnails4>
                <Thumbnails5 >
                  <HpMovieThumbnail21   />
                  <HpMovieThumbnail22   />
                </Thumbnails5>
              </Movies1>
            </CardInfo2>
          </SecComingSoon>
        </ContentAndMask>
      </TopAndMask>
      <MovieFooter1   />
    </ScreenMobile>
  );
}

export default MovieHomePage;
