/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import { OutlinedTextProps } from 'types';

 
const OutlinedText1: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `157px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const HelloWorld: any = styled("img")({  
  height: `auto`,  
  width: `120.16px`,  
  position: `absolute`,  
  left: `17px`,  
  top: `12px`,  
});
 
function OutlinedText(props: OutlinedTextProps): JSX.Element {
  return (
    <OutlinedText1  className={props.className}   >
      <HelloWorld  src={`assets/images/OutlinedText_HELLO_WORLD_1.svg`} alt={"HELLO WORLD"}/>
    </OutlinedText1>
  );
}

export default OutlinedText;
