/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import { PathProps } from 'types';

 
const Path1: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `157px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Vector1: any = styled("img")({  
  height: `auto`,  
  width: `88.5px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `18px`,  
});
 
function Path(props: PathProps): JSX.Element {
  return (
    <Path1  className={props.className}   >
      <Vector1  src={`assets/images/Path_Vector_1.svg`} alt={"Vector 1"}/>
    </Path1>
  );
}

export default Path;
