/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Rating4 from 'src/components/Rating4/Rating4';

 
const Repeat21 = styled("div")({  
  display: `grid`,  
  position: `relative`,  
  isolation: `isolate`,  
  padding: `10px`,  
  boxSizing: `border-box`,  
  width: "100%",  
  gridTemplateColumns: `repeat(auto-fit, minmax(300px, 1fr))`,  
  columnGap: `10px`,  
  rowGap: `10px`,  
});
  
const Rating41 = styled(Rating4)(({ theme }) =>({  
  width: `300px`,  
  margin: `0px`,  
}));
 
function Repeat2(props) {
  
    return (
    <Repeat21  className={props.className}   >
      {undefined && undefined.map((undefined, index) => {
        return (
          <Rating41  key={index}  />
        );
      })}
    </Repeat21>
  );
}

export default Repeat2;
