/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Helmet } from 'react-helmet';
import Gettyimages125755349Image from 'src/assets/images/Frame23_gettyimages_1257553494_1.png';
import Star1Image from 'src/assets/images/Frame23_Star_1.png';
import QuestLogoSquare1Image from 'src/assets/images/Frame23_Quest_Logo_square_1.svg';
import { styled } from '@mui/material/styles';
import Shape3 from 'src/components/Shape3/Shape3';
import ImageTest from 'src/components/ImageTest/ImageTest';
import Shape4Rotated from 'src/components/Shape4Rotated/Shape4Rotated';
import { animated, useSpring, easings } from 'react-spring';

 
const Frame231 = animated(styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  borderRadius: `5px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `60px 10px`,  
  boxSizing: `border-box`,  
  height: "100%",  
  width: "100%",  
}));
  
const Shape31 = styled(Shape3)(({ theme }) =>({  
  width: `153px`,  
  height: `157px`,  
  margin: `0px`,  
}));
  
const Gettyimages125755349 = styled("img")({  
  height: `237px`,  
  width: `218px`,  
  objectFit: `cover`,  
  margin: `0px 0px 0px 34px`,  
});
  
const Frame24 = animated(styled("div")({  
  backgroundColor: `rgba(188, 44, 53, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `244px`,  
  height: `225px`,  
  margin: `0px 0px 0px 34px`,  
  overflow: `hidden`,  
}));
  
const ImageTest1 = animated(styled(ImageTest)(({ theme }) =>({  
  margin: `0px 0px 0px 34px`,  
})));
  
const Sometext = animated(styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Inter`,  
  fontWeight: `900`,  
  fontSize: `32px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `33px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 34px`,  
}));
  
const Shape4Rotated1 = styled(Shape4Rotated)(({ theme }) =>({  
  width: `153px`,  
  height: `157px`,  
  margin: `0px 0px 0px 34px`,  
}));
  
const Star1 = styled("img")({  
  height: `85px`,  
  width: `85px`,  
  margin: `0px 0px 0px 34px`,  
});
  
const QuestLogoSquare1 = styled("img")({  
  height: `auto`,  
  width: `94.71px`,  
  objectFit: `cover`,  
  margin: `0px 0px 0px 34px`,  
});
 
function Frame23(props) {
  
  
  const [Frame231Spring, Frame231Api] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeOutExpo']
    },
    delay: 0,
    from: { opacity: 1  },
  }));

  const [Frame24Spring, Frame24Api] = useSpring(() => ({
    config: {
      duration: 750,
      easing: easings['easeInOutExpo']
    },
    delay: 0,
    from: { transform: "translateX(0px)"  },
  }));

  const [ImageTest1Spring, ImageTest1Api] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeOutExpo']
    },
    delay: 0,
    from: { opacity: 1  },
  }));

  const [SometextSpring, SometextApi] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeOutExpo']
    },
    delay: 0,
    from: { opacity: 1  },
  }));
  return (
    <Frame231 onClick={() => {  Frame231Api.start({ ...{ opacity: 0  }, delay: 0 });  }}  className={props.className}    style={{ ...Frame231Spring }}>
      <Helmet>
        <title>Frame 23</title>
      </Helmet>
      <Shape31   />
      <Gettyimages125755349  src={Gettyimages125755349Image} alt={"gettyimages-1257553494 1"}/>
      <Frame24 onClick={() => {  Frame24Api.start({ ...{ transform: "translateX(100px)"  }, delay: 0 });  }}  style={{ ...Frame24Spring }}>
      </Frame24>
      <ImageTest1   onClick={() => {  ImageTest1Api.start({ ...{ opacity: 0  }, delay: 0 });  }}  style={{ ...ImageTest1Spring }}/>
      <Sometext  onClick={() => {  SometextApi.start({ ...{ opacity: 0  }, delay: 0 });  }} style={{ ...SometextSpring }}>
        {`SOMETEXT`}
          </Sometext>
      <Shape4Rotated1   />
      <Star1  src={Star1Image} alt={"Star 1"}/>
      <QuestLogoSquare1  src={QuestLogoSquare1Image} alt={"Quest_Logo_square 1"}/>
    </Frame231>
  );
}

export default Frame23;
