/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

 
const Frame301 = styled("div")({  
  backgroundColor: `rgba(255, 215, 215, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  overflow: `hidden`,  
});
 
function Frame30(props) {
  
    return (
    <Frame301  className={props.className}   >
    </Frame301>
  );
}

export default Frame30;
