/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import HelloWorldImage from 'src/assets/images/OutlinedText_HELLO_WORLD_1.svg';
import { styled } from '@mui/material/styles';
import { animated, useSpring, easings } from 'react-spring';

 
const OutlinedText1 = animated(styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100vw",  
  height: `157px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
}));
  
const HelloWorld = animated(styled("img")({  
  height: `auto`,  
  width: `120.16px`,  
  position: `absolute`,  
  left: `17px`,  
  top: `12px`,  
}));
 
function OutlinedText(props) {
  
  
  const [OutlinedText1Spring, OutlinedText1Api] = useSpring(() => ({
    config: {
      duration: 250,
      easing: easings['easeOutExpo']
    },
    delay: 0,
    from: { opacity: 1  },
  }));

  const [HelloWorldSpring, HelloWorldApi] = useSpring(() => ({
    config: {
      duration: 750,
      easing: easings['easeInOutExpo']
    },
    delay: 0,
    from: { transform: "translateX(0px)" , opacity: 1  },
  }));
  return (
    <OutlinedText1 onClick={() => {  OutlinedText1Api.start({ ...{ opacity: 1  }, delay: 0 });  }}  className={props.className}    style={{ ...OutlinedText1Spring }}>
      <HelloWorld onClick={() => {  HelloWorldApi.start({ ...{ transform: "translateX(-100px)" , opacity: 0  }, delay: 0 });  }}  style={{ ...HelloWorldSpring }} src={HelloWorldImage} alt={"HELLO WORLD"}/>
    </OutlinedText1>
  );
}

export default OutlinedText;
