/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import { ImageTestProps } from 'types';

 
const ImageTest1: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `157px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const QuestLogoSquare1: any = styled("img")({  
  height: `auto`,  
  width: `94.71px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `44px`,  
  top: `46px`,  
});
 
function ImageTest(props: ImageTestProps): JSX.Element {
  return (
    <ImageTest1  className={props.className}   >
      <QuestLogoSquare1  src={`assets/images/ImageTest_Quest_Logo_square_1.svg`} alt={"Quest_Logo_square 1"}/>
    </ImageTest1>
  );
}

export default ImageTest;
