/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import { Shape5Props } from 'types';

 
const Shape51: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `138px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Arrow1: any = styled("img")({  
  height: `auto`,  
  width: `108px`,  
  position: `absolute`,  
  left: `15px`,  
  top: `69px`,  
});
 
function Shape5(props: Shape5Props): JSX.Element {
  return (
    <Shape51  className={props.className}   >
      <Arrow1  src={`assets/images/Shape5_Arrow_1.svg`} alt={"Arrow 1"}/>
    </Shape51>
  );
}

export default Shape5;
