/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { Radio, FormControlLabel, Switch } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const Frame11 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `24px 90px`,  
  boxSizing: `border-box`,  
  height: `280px`,  
  width: "100%",  
});
  
const FormControlLabel1 = styled(FormControlLabel)({  
  margin: `0px`,  
});
  
const FormControlLabel2 = styled(FormControlLabel)({  
  margin: `24px 0px 0px 0px`,  
});
  
const FormControlLabel3 = styled(FormControlLabel)({  
  margin: `24px 0px 0px 0px`,  
});
  
const FormControlLabel4 = styled(FormControlLabel)({  
  margin: `24px 0px 0px 0px`,  
});
 
function Frame1(props) {
  
    return (
    <Frame11  className={props.className}   >
      <FormControlLabel1  control={<Radio color="primary" size="medium" />} />
      <FormControlLabel2  control={<Radio color="primary" size="medium" />} />
      <FormControlLabel3 control={<Switch defaultChecked={true} color="primary" size="medium" />} label={"Label"} />
      <FormControlLabel4 control={<Switch defaultChecked={true} color="primary" size="medium" />} label={"Label"} />
    </Frame11>
  );
}

export default Frame1;
